### PR TITLE
Redis Cluster Experiments

### PR DESCRIPTION
**Pull request by jujaga**
# Description

This PR aims to determine if Redis Cluster is viable. DO NOT MERGE!

[SHOWCASE-1949](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-1949)

## Types of changes

New feature (non-breaking change which adds functionality)

Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] I have read the [CONTRIBUTING](CONTRIBUTING.md) doc
- [ ] I have checked that unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have updated the OpenAPI 3.0 `v*.api-spec.yaml` documentation (if appropriate)
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by bcgov-nr-csst** [comment]
PR Deployed at: https://ches-pr-70-9f0fbe-dev.pathfinder.gov.bc.ca

**Comment by bcgov-nr-csst** [comment]
PR Deployed at: https://ches-pr-70-9f0fbe-dev.pathfinder.gov.bc.ca

**Comment by bcgov-nr-csst** [comment]
PR Deployed at: https://ches-pr-70-9f0fbe-dev.pathfinder.gov.bc.ca

**Comment by jujaga** [comment]
It appears Redis Cluster is reasonably viable with our initial testing. We will be proceeding with this version of HA on OCP4. Closing this PR to begin preparing for the migration

**Pull request closed without merging**
