### PR TITLE
Redis Sentinel Experiments

### PR DESCRIPTION
**Pull request by jujaga**
# Description

This PR aims to determine if Redis Sentinel is viable. DO NOT MERGE!

[SHOWCASE-1949](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-1949)

## Types of changes

New feature (non-breaking change which adds functionality)

Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] I have read the [CONTRIBUTING](CONTRIBUTING.md) doc
- [ ] I have checked that unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have updated the OpenAPI 3.0 `v*.api-spec.yaml` documentation (if appropriate)
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by bcgov-nr-csst** [comment]
PR Deployed at: https://ches-pr-69-9f0fbe-dev.pathfinder.gov.bc.ca

**Comment by jujaga** [comment]
Unable to get Redis Sentinel to work cleanly with ioredis. Getting hosts of errors along the lines of it connecting to the replica and not auto-reconnecting to master as advertised.
```
BRPOPLPUSH ReplyError: READONLY You can't write against a read only replica.
    at parseError (/opt/app-root/src/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/opt/app-root/src/node_modules/redis-parser/lib/parser.js:302:14) {
  command: {
    name: 'brpoplpush',
    args: [ 'bull:ches:wait', 'bull:ches:active', '5' ]
  }
}
```
```
WARN ioredis Connection is READONLY. Attempting to reconnect to master...
ERR! onError A Job failed ERR Error running script (call to f_d4d1d1b62afa6d576d81cfbecc482ad7e516d172): @user_script:30: @user_script: 30: -READONLY You can't write against a read only replica.
```

**Comment by bcgov-nr-csst** [comment]
PR Deployed at: https://ches-pr-69-9f0fbe-dev.pathfinder.gov.bc.ca

**Comment by bcgov-nr-csst** [comment]
PR Deployed at: https://ches-pr-69-9f0fbe-dev.pathfinder.gov.bc.ca

**Comment by bcgov-nr-csst** [comment]
PR Deployed at: https://ches-pr-69-9f0fbe-dev.pathfinder.gov.bc.ca

**Comment by bcgov-nr-csst** [comment]
PR Deployed at: https://ches-pr-69-9f0fbe-dev.pathfinder.gov.bc.ca

**Comment by jujaga** [comment]
Attempted to isolate Redis connection instantiation, but had no luck. Kept getting variants of the following error:
```
ERR! Error: connect ECONNREFUSED 127.0.0.1:6379
```
From what I can tell, it "looks" like ioredis is able to connect to sentinel correctly. However, I'm suspecting that sentinel itself is miss reporting the proper IP of the redis server that its monitoring. Since sentinel is co-located with redis, it is highly likely sentinel is reporting redis as localhost. Was able to verify we were not telling ioredis to connect to localhost from any of our code.

**Pull request closed without merging**
