### PR TITLE
Add PGP Encryption and Signing support

### PR DESCRIPTION
**Pull request by jujaga**
# Description

This PR adds OpenPGP encryption and signing support to CHES.

**Other changes:**
- Bump version to 1.1.0
- Change nodemailer transport object to not use singleton pattern
- Update OpenAPI spec to optionally output in json format

[SHOWCASE-1453](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-1453)

## Types of changes

New feature (non-breaking change which adds functionality)
Documentation (non-breaking change with enhancements to documentation)

## Checklist

- [x] I have read the [CONTRIBUTING](CONTRIBUTING.md) doc
- [x] I have checked that unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have updated the OpenAPI 3.0 `v*.api-spec.yaml` documentation (if appropriate)
- [x] I have added necessary documentation (if appropriate)

## Further comments

Visit the [user manual](https://github.com/jujaga/common-hosted-email-service/blob/feature/pgp/app/README.md#openpgp-encryption) for an in-depth explanation on how to utilize the proposed OpenPGP feature.
Visit [https://ches-pr-51-9f0fbe-dev.pathfinder.gov.bc.ca/api/v1/docs](https://ches-pr-51-9f0fbe-dev.pathfinder.gov.bc.ca/api/v1/docs) for the backwards compatible API change proposal to CHES to support PGP.

**Outstanding issues:**
- ~~No validation of PGP Key block attributes~~
- ~~Potential LGPL license incompatibility~~
- Insecure version of OpenPGP used

### CODE REVIEW

**Comment by bcgov-nr-csst** [comment]
SonarQube Analysis: https://sonarqube-9f0fbe-tools.pathfinder.gov.bc.ca/dashboard?id=common-hosted-email-service-pr-51

**Comment by bcgov-nr-csst** [comment]
SonarQube Analysis: https://sonarqube-9f0fbe-tools.pathfinder.gov.bc.ca/dashboard?id=common-hosted-email-service-pr-51

**Review by itchison — COMMENTED** [review]
The https://github.com/bcgov/moh-prime/ team (Thanks @james-hollinger ) took a look at this PR. Some feedback:
1. We'd like to see the encryption and the signing separated. We'd like to be able to sign emails without the requirement of knowing a password.
2. How does the recipient trust the certificate? Especially if we can generate it on any PC? Could it use https://www2.gov.bc.ca/gov/content/governments/services-for-government/bc-bid-resources/goods-and-services-catalogue/digital-certificate-service ?
3. I dislike that we have to send you the private key. We're handing you a very powerful key with a lot of trust.

**Comment by jujaga** [comment]
Hi @itchison thank you for evaluating this PR! Let me respond to some of your feedback thoughts:

1. The library we are leveraging does not support the separation of encryption and signing. To pursue this separation, we would need to develop our own intermediary nodemailer plugin from scratch as nothing currently exists with that decoupled in the nodemailer ecosystem.
2. Taking a quick look at DCS, it appears that trust is handled and asserted via .p7m certificates and third-party software such as Entrust Entelligence and SafeNet. Unfortunately this does not look compatible with OpenPGP at all, which instead manages trust through a decentralized web of trust concept. These two technologies have two fundamentally different ways of asserting the trustability of a signature.
3. The current implementation is capable of encrypting a message using a one or a set of only public keys as only the holder(s) of the associated private key(s) will be able to decrypt the contents. This provides a guarantee that the message went to the "right" recipients.
The act of signing an encrypted messages provides assurances to the "right" recipients that the message came from a known and trusted source. However, the act of signing a message requires access to a private key because the CHES service is performing the signing on your behalf, using the private key you provided. Without providing a private key, our service can not sign a message on your behalf; instead, you must sign the message contents yourself first before invoking the CHES API.

With the above in mind, please let us know your thoughts and what potential next steps we could consider.

**Comment by jujaga** [comment]
This feature proposal has gone stale. Closing for now and will revisit in future if it becomes relevant again.

**Pull request closed without merging**
